version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: test
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
